"""
Uncoder IO Community Edition License
-----------------------------------------------------------------
Copyright (c) 2024 SOC Prime, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-----------------------------------------------------------------
"""

import copy
import json
from typing import Optional

from app.translator.const import DEFAULT_VALUE_TYPE
from app.translator.core.custom_types.tokens import LogicalOperatorType, OperatorType
from app.translator.core.custom_types.values import ValueType
from app.translator.core.mapping import SourceMapping
from app.translator.core.models.platform_details import PlatformDetails
from app.translator.core.models.query_container import MetaInfoContainer, TokenizedQueryContainer
from app.translator.core.models.query_tokens.field_value import FieldValue
from app.translator.core.render import PlatformQueryRender
from app.translator.managers import render_manager
from app.translator.platforms.logrhythm_aie.const import (
    DEFAULT_LOGRHYTHM_AIE_RULE,
    MATCH_TYPE,
    SEVERITY_TO_RISK_RATING,
    logrhythm_aie_rule_details,
)
from app.translator.platforms.logrhythm_aie.escape_manager import logrhythm_aie_escape_manager
from app.translator.platforms.logrhythm_aie.mapping import LogRhythmAIEMappings, logrhythm_aie_mappings
from app.translator.tools.utils import get_rule_description_str

_AUTOGENERATED_TEMPLATE = "Autogenerated LogRhythm AIE Rule"


@render_manager.register
class LogRhythmAIERuleRender(PlatformQueryRender):
    """
    LogRhythm AI Engine Rule renderer for Uncoder.io.

    Unlike typical query renderers, AIE doesn't have a text-based query language.
    Instead, we build JSON filter structures directly from SIGMA tokens.

    This renderer does NOT extend PlatformQueryRender because AIE doesn't have
    a query language - it's purely JSON-based filter structures.
    """

    details: PlatformDetails = logrhythm_aie_rule_details
    mappings: LogRhythmAIEMappings = logrhythm_aie_mappings
    comment_symbol = "//"
    is_single_line_comment = True

    def __init__(self):
        super().__init__()
        self.escape_manager = logrhythm_aie_escape_manager
        # Initialize platform functions for the base class
        self.init_platform_functions()

    def _get_operator(self, operator: str) -> int:
        """
        Map SIGMA operator to LogRhythm operator enum.

        LogRhythm operators:
        0 = EqualTo, 1 = NotEqualTo, 2 = Contains, 3 = NotContains,
        4 = BeginsWith, 5 = EndsWith
        """
        if operator in [OperatorType.EQ]:
            return 0  # EqualTo
        elif operator in [OperatorType.NOT_EQ]:
            return 1  # NotEqualTo
        elif operator in [OperatorType.CONTAINS, OperatorType.NOT_CONTAINS]:
            return 2  # Contains
        elif operator in [OperatorType.STARTSWITH, OperatorType.NOT_STARTSWITH]:
            return 4  # BeginsWith
        elif operator in [OperatorType.ENDSWITH, OperatorType.NOT_ENDSWITH]:
            return 5  # EndsWith
        elif operator in [OperatorType.REGEX, OperatorType.NOT_REGEX]:
            return 2  # Contains (treat regex as contains)
        else:
            return 0  # Default to EqualTo

    def _is_negated_operator(self, operator: str) -> bool:
        """Check if operator is negated (NOT_*)"""
        return operator in [
            OperatorType.NOT_EQ,
            OperatorType.NOT_CONTAINS,
            OperatorType.NOT_STARTSWITH,
            OperatorType.NOT_ENDSWITH,
            OperatorType.NOT_REGEX,
        ]

    def _token_to_field_filter(
        self,
        token: FieldValue,
        source_mapping: SourceMapping
    ) -> list[dict]:
        """
        Convert a FieldValue token to one or more LogRhythm field_filters.

        Returns list of filters because one SIGMA field may map to multiple LogRhythm fields.

        Output format matches AirxInterop.exe expectations:
        {
            "filter_type": int,      // FieldFilterTypeEnum ID
            "operator": int,         // 0=EqualTo, 2=Contains, 4=BeginsWith, 5=EndsWith
            "filter_mode": int,      // 0=IS NOT, 1=IS (default)
            "values": [...]          // Array of string/int values
        }
        """
        # Get the SIGMA field name
        sigma_field_name = token.field.source_name if hasattr(token.field, 'source_name') else str(token.field)

        # Map SIGMA field to LogRhythm FieldFilterTypeEnum ID
        field_id = self.mappings.get_field_id(sigma_field_name)

        # Get operator enum value
        operator = self._get_operator(token.operator.token_type)

        # Determine filter_mode (0 = IS NOT, 1 = IS)
        # Negated operators set filter_mode to 0
        filter_mode = 0 if self._is_negated_operator(token.operator.token_type) else 1

        # Handle list values - all go in single filter's values array
        values = token.value if isinstance(token.value, list) else [token.value]

        # Convert values to strings (except for numeric fields)
        converted_values = [str(v) for v in values]

        # Return single filter with all values
        return [{
            "filter_type": field_id,
            "operator": operator,
            "filter_mode": filter_mode,
            "values": converted_values
        }]

    def _determine_field_operator(
        self,
        current_idx: int,
        tokens: list,
        prev_was_or: bool
    ) -> str:
        """
        Determine field_operator based on surrounding logical operators.

        Field operator logic:
        - "And": Start/continue AND chain
        - "Or": Start/continue OR chain
        - "OrPrevious": Switch from AND to OR
        - "AndPrevious": Switch from OR to AND
        """
        # Check next token
        next_token = tokens[current_idx + 1] if current_idx + 1 < len(tokens) else None

        # First filter gets "And" by default
        if current_idx == 0 or (current_idx == 1 and not isinstance(tokens[0], FieldValue)):
            return "And"

        # If next token is OR, we need to check if we're starting or continuing OR chain
        if next_token and next_token.token_type == LogicalOperatorType.OR:
            if prev_was_or:
                return "Or"  # Continue OR chain
            else:
                return "OrPrevious"  # Switch from AND to OR

        # If next token is AND or no token
        if not next_token or next_token.token_type == LogicalOperatorType.AND:
            if prev_was_or:
                return "AndPrevious"  # Switch from OR to AND
            else:
                return "And"  # Continue AND chain

        return "And"

    def _tokens_to_msg_filters(
        self,
        tokens: list,
        source_mapping: SourceMapping
    ) -> list[dict]:
        """
        Convert SIGMA tokens to LogRhythm msg_filters structure.

        Handles field_operator logic for AND/OR combinations.

        Returns list of msg_filter objects, each with msg_filter_type and field_filters.
        """
        field_filters = []
        prev_was_or = False

        for idx, token in enumerate(tokens):
            if isinstance(token, FieldValue):
                # Convert token to field filters
                filters = self._token_to_field_filter(token, source_mapping)

                # Determine field_operator
                field_operator = self._determine_field_operator(idx, tokens, prev_was_or)

                # Add filters with field_operator
                for filter_dict in filters:
                    filter_dict["field_operator"] = field_operator
                    field_filters.append(filter_dict)

            elif hasattr(token, 'token_type') and token.token_type == LogicalOperatorType.OR:
                prev_was_or = True
            elif hasattr(token, 'token_type') and token.token_type == LogicalOperatorType.AND:
                prev_was_or = False

        # Wrap field_filters in msg_filter structure
        return [{
            "msg_filter_type": 1,
            "field_filters": field_filters
        }]

    def _detect_aggregation(self, meta_info: MetaInfoContainer) -> Optional[str]:
        """
        Detect aggregation type from SIGMA correlation metadata.

        Returns: "threshold", "unique_values", or None
        """
        # Check for SIGMA correlation fields
        if hasattr(meta_info, 'correlation') and meta_info.correlation:
            correlation_type = getattr(meta_info.correlation, 'type', None)

            if correlation_type == 'event_count':
                return 'threshold'
            elif correlation_type == 'value_count':
                return 'unique_values'

        # Check for timeframe (indicates aggregation)
        if meta_info.timeframe:
            # Default to threshold if timeframe present but no correlation type
            return 'threshold'

        return None

    def _select_group_by_fields(
        self,
        meta_info: MetaInfoContainer,
        msg_filters: dict
    ) -> list[int]:
        """
        Select appropriate group_by_fields based on log source and filters.

        Strategy from LogRhythm expert:
        - Network traffic → Source (16) - Host Origin
        - System activity → Destination (17) - Host Impacted
        - Authentication → Source (16) - Host Origin

        FieldEnum values (NOT FieldFilterTypeEnum):
        - 16: Source (Host Origin - accepts hostname, IP, or both)
        - 17: Destination (Host Impacted - accepts hostname, IP, or both)
        - 18: Service (Application)
        - 24: SIP (Source IP)
        """
        parsed_logsources = getattr(meta_info, 'parsed_logsources', {})
        product = parsed_logsources.get('product', [''])[0].lower() if 'product' in parsed_logsources else ''
        category = parsed_logsources.get('category', [''])[0].lower() if 'category' in parsed_logsources else ''
        service = parsed_logsources.get('service', [''])[0].lower() if 'service' in parsed_logsources else ''

        # Network traffic rules
        NETWORK_SOURCES = ['network', 'firewall', 'proxy', 'dns', 'web', 'zeek', 'suricata', 'paloalto']
        if category in NETWORK_SOURCES or product in NETWORK_SOURCES:
            return [16]  # Source (Host Origin)

        # System activity rules
        SYSTEM_SOURCES = ['sysmon', 'process_creation', 'file_event', 'registry_event',
                          'driver_load', 'image_load', 'ps_script', 'pipe_created']
        if category in SYSTEM_SOURCES or service == 'sysmon' or product == 'sysmon':
            return [17]  # Destination (Host Impacted)

        # Authentication rules
        AUTH_SOURCES = ['authentication', 'okta', 'azure', 'azuread', 'linux']
        if category in AUTH_SOURCES or service == 'security':
            return [16]  # Source (Host Origin)

        # Fallback: Destination (Host Impacted) is most universally populated
        return [17]

    def _build_rule_blocks(
        self,
        tokens: list,
        source_mapping: SourceMapping,
        meta_info: MetaInfoContainer
    ) -> list[dict]:
        """Build rule blocks based on aggregation detection"""
        # Convert tokens to msg_filters
        msg_filters = self._tokens_to_msg_filters(tokens, source_mapping)

        # Detect aggregation type
        aggregation_type = self._detect_aggregation(meta_info)

        # Select group_by_fields
        group_by_fields = self._select_group_by_fields(meta_info, msg_filters)

        if aggregation_type == 'threshold':
            # ThresholdObservedRuleBlock
            block = {
                "block_type": "ThresholdObservedRuleBlock",
                "msg_filters": msg_filters,
                "group_by_fields": group_by_fields,
                "threshold_count": getattr(meta_info.correlation, 'threshold', 5) if hasattr(meta_info, 'correlation') else 5,
                "query_duration_seconds": int(meta_info.timeframe.total_seconds()) if meta_info.timeframe else 300
            }
        elif aggregation_type == 'unique_values':
            # UniqueValuesObservedRuleBlock
            block = {
                "block_type": "UniqueValuesObservedRuleBlock",
                "msg_filters": msg_filters,
                "group_by_fields": group_by_fields,
                "unique_count": getattr(meta_info.correlation, 'threshold', 5) if hasattr(meta_info, 'correlation') else 5,
                "query_duration_seconds": int(meta_info.timeframe.total_seconds()) if meta_info.timeframe else 300
            }
        else:
            # LogObservedRuleBlock (default)
            block = {
                "block_type": "LogObservedRuleBlock",
                "msg_filters": msg_filters,
                "group_by_fields": group_by_fields
            }

        return [block]

    def _extract_mitre_metadata(self, meta_info: MetaInfoContainer) -> dict:
        """Extract MITRE ATT&CK metadata from meta_info"""
        mitre_data = {}

        if not meta_info.mitre_attack:
            return mitre_data

        # Extract tactics
        if meta_info.mitre_attack.tactics:
            tactics = []
            for tactic in meta_info.mitre_attack.tactics:
                tactics.append({
                    "id": tactic.external_id,
                    "name": tactic.name
                })
            mitre_data["tactics"] = tactics

        # Extract techniques
        if meta_info.mitre_attack.techniques:
            techniques = []
            for technique in meta_info.mitre_attack.techniques:
                techniques.append({
                    "id": technique.technique_id,
                    "name": technique.name
                })
            mitre_data["techniques"] = techniques

        return mitre_data

    def finalize_query(
        self,
        tokens: list,
        source_mapping: SourceMapping,
        meta_info: Optional[MetaInfoContainer] = None,
        not_supported_functions: Optional[list] = None,
        unmapped_fields: Optional[list[str]] = None,
        *args,
        **kwargs,
    ) -> str:
        """
        Build LogRhythm AIE JSON rule from tokens.

        Unlike typical query renderers, this builds JSON directly from tokens.
        """
        # Start with default rule template
        rule = copy.deepcopy(DEFAULT_LOGRHYTHM_AIE_RULE)

        # Build rule blocks from tokens
        rule["blocks"] = self._build_rule_blocks(tokens, source_mapping, meta_info)

        # Set metadata
        rule["name"] = meta_info.title or _AUTOGENERATED_TEMPLATE
        rule["short_desc"] = meta_info.title or _AUTOGENERATED_TEMPLATE
        rule["long_desc"] = get_rule_description_str(
            description=meta_info.description or _AUTOGENERATED_TEMPLATE,
            author=meta_info.author,
            license_=meta_info.license,
        )

        # Set risk rating from severity
        rule["risk_rating"] = SEVERITY_TO_RISK_RATING.get(meta_info.severity, 5)

        # Add MITRE metadata
        mitre_data = self._extract_mitre_metadata(meta_info)
        if mitre_data:
            rule["mitre"] = mitre_data

        # Serialize to JSON
        json_rule = json.dumps(rule, indent=4, sort_keys=False)

        # Add unmapped fields and unsupported functions as comments
        json_rule = self.wrap_with_unmapped_fields(json_rule, unmapped_fields)
        json_rule = self.wrap_with_not_supported_functions(json_rule, not_supported_functions)

        return json_rule

    def generate_from_tokenized_query_container(self, query_container: TokenizedQueryContainer) -> str:
        """Generate AIE rule from tokenized query container"""
        # Get source mappings
        source_mappings = self.mappings.get_source_mappings_by_ids(
            query_container.meta_info.source_mapping_ids
        )

        # Use first source mapping (AIE doesn't support multiple source mappings in one rule)
        source_mapping = source_mappings[0] if source_mappings else SourceMapping()

        # Check field mappings
        unmapped_fields = self.mappings.check_fields_mapping_existence(
            query_container.meta_info.query_fields,
            query_container.meta_info.function_fields_map,
            self.platform_functions.manager.supported_render_names,
            source_mapping,
        )

        # Build rule from tokens
        return self.finalize_query(
            tokens=query_container.tokens,
            source_mapping=source_mapping,
            meta_info=query_container.meta_info,
            not_supported_functions=query_container.functions.not_supported,
            unmapped_fields=unmapped_fields,
        )

    def generate(self, raw_query_container, tokenized_query_container: Optional[TokenizedQueryContainer]):
        """Main entry point for rule generation"""
        if tokenized_query_container:
            return self.generate_from_tokenized_query_container(tokenized_query_container)

        # AIE doesn't support raw query conversion
        return json.dumps({
            "error": "LogRhythm AIE requires tokenized SIGMA input. Raw query conversion is not supported."
        }, indent=4)
