"""
Uncoder IO Community Edition License
-----------------------------------------------------------------
Copyright (c) 2024 SOC Prime, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-----------------------------------------------------------------
"""

from app.translator.core.custom_types.meta_info import SeverityType
from app.translator.core.models.platform_details import PlatformDetails

# Fallback field for unmapped SIGMA fields
# Command (112) is moderately expensive but often matches process/command-related fields
# Alternative: Message (35) searches entire raw log (very expensive, last resort only)
UNMAPPED_FIELD_DEFAULT = 112  # Command field

# Default AIE rule template (minimal LogObservedRuleBlock)
DEFAULT_LOGRHYTHM_AIE_RULE = {
    "name": "Default AI Engine Rule",
    "short_desc": "Autogenerated LogRhythm AIE Rule",
    "long_desc": "Autogenerated LogRhythm AIE Rule",
    "risk_rating": 5,  # Medium severity (0-9 scale)
    "alarm_enabled": True,
    "rule_enabled": False,  # Disabled by default for safety
    "blocks": [
        {
            "block_type": "LogObservedRuleBlock",
            "msg_filters": [],
            "group_by_fields": [17]  # Default: Destination (Host Impacted)
        }
    ]
}

# Platform identification
PLATFORM_DETAILS = {
    "group_id": "logrhythm-aie",
    "group_name": "LogRhythm SIEM"
}

LOGRHYTHM_AIE_RULE_DETAILS = {
    "platform_id": "logrhythm-aie-rule",
    "name": "LogRhythm AI Engine Rule",
    "platform_name": "AI Engine Rule",
    **PLATFORM_DETAILS
}

logrhythm_aie_rule_details = PlatformDetails(**LOGRHYTHM_AIE_RULE_DETAILS)

# SIGMA severity to LogRhythm risk_rating mapping
# Valid range: 0-9 (value 10+ causes LogRhythm UI crash)
SEVERITY_TO_RISK_RATING = {
    SeverityType.informational: 1,
    SeverityType.low: 3,
    SeverityType.medium: 5,
    SeverityType.high: 7,
    SeverityType.critical: 9,  # NOT 10 - confirmed max is 9
}

# MatchTypeEnum values for operators
MATCH_TYPE = {
    "Value": 0,       # Exact match
    "SQLPattern": 1,  # SQL LIKE pattern
    "Regex": 2,       # Regular expression
    "Term": 3         # Term match
}
